
# .dacrew-example.yml
# Project-specific configuration for DaCrew.
# Copy this file to .dacrew.yml in your project root and update it with your values.
#
# Values here override or extend those in ~/.dacrew/config.yml for this project.

# =====================================================================
# Project Configuration
# =====================================================================
project:
  # Unique identifier for this project (must match workspace name)
  key: "dc"

  # Jira project key (e.g., ABC)
  jira_project_key: "BTS"

# =====================================================================
# Build & Test Commands
# =====================================================================
commands:
  # Build command relative to the workspace/current directory
  build: "./gradlew build"

  # Test command relative to the workspace/current directory
  test: "./gradlew test"

# =====================================================================
# Git Settings
# =====================================================================
git:
  # Default branch prefix for branches created by dacrew
  default_branch_prefix: "dacrew/"

  # Commit message template
  # Available placeholders: {ISSUE_ID}, {ISSUE_TITLE}
  commit_template: "Implementing {ISSUE_ID}: {ISSUE_TITLE}"

# =====================================================================
# Jira Configuration (Optional Overrides)
# =====================================================================
jira:
  # Override the global Jira URL if needed (optional)
  # url: "https://custom-jira-instance.atlassian.net"

# =====================================================================
# AI Configuration (Optional Overrides)
# =====================================================================
ai:
  # Project-specific AI settings (if needed)
  # model: "gpt-4"
  # temperature: 0.5

# =====================================================================
# Documentation and Knowledge Base
# =====================================================================
docs:
  # Paths to domain documentation or knowledge files to embed
  # - "docs/architecture.md"
  # - "docs/design-specs/"
