
# .dacrew-example.yml
# Project-specific configuration for DaCrew.
# Copy this file to .dacrew.yml in your project root and update it with your values.
#
# Values here override or extend those in ~/.dacrew/config.yml for this project.
# DO NOT PLACE API KEYS IN THIS FILE

# =====================================================================
# Project Configuration
# =====================================================================
project: "bts"  # Unique identifier for this project (must match workspace name)

# =====================================================================
# Embedding Configuration
# =====================================================================
embedding:
  # ---------------------------------------------------------
  # Codebase Embedding
  # ---------------------------------------------------------
  codebase:
    path: "./"  # Path to the project source root
    include_patterns:
      - "src/**/*.java"
      - "src/**/*.py"
    exclude_patterns:
      - "node_modules/**"
      - "build/**"

  # ---------------------------------------------------------
  # Jira Issues Embedding
  # ---------------------------------------------------------
  issues:
    exclude_statuses: ["Cancelled", "Archived"]

  # ---------------------------------------------------------
  # Documents & Web Embedding
  # ---------------------------------------------------------
  documents:
    paths:
      - "docs/Python_CLI_Application.pdf"
      - "docs/Python_Tips.txt"
      - "docs/README.me"
    urls:
      - "https://realpython.com/python-click/"
      - "https://gist.github.com/ruimaranhao/4e18cbe3dad6f68040c32ed6709090a3"
      - "https://dev.to/devasservice/python-best-practices-writing-clean-efficient-and-maintainable-code-34bj"

# =====================================================================
# Git Settings
# =====================================================================
git:
  # Default branch prefix for branches created by dacrew
  default_branch_prefix: "dacrew/"

  # Commit message template
  # Available placeholders: {ISSUE_ID}, {ISSUE_TITLE}
  commit_template: "Implementing {ISSUE_ID}: {ISSUE_TITLE}"

# =====================================================================
# Jira Configuration
# =====================================================================
jira:
  # URL to your Jira instance (e.g., https://yourcompany.atlassian.net)
  url: "https://karakun-agent.atlassian.net"

  # Jira project key (e.g., ABC)
  jira_project_key: "BTS"

  # Default user ID (often the username or email)
  user_id: "mike.mannion@karakun.com"

  # Maximum number of jira issues fetched for any query
  fetch_limit: 500

crew:
  name: java_gradle_crew

  # =====================================================================
  # Generation (Build & Test Commands)
  # =====================================================================

  # Build command relative to the workspace/current directory (optional)
  build_command: "./gradlew build"

  # Test command relative to the workspace/current directory (optional)
  test_command: "./gradlew test"
