jira:
  url: https://your-domain.atlassian.net
  user_id: your-user@example.com
projects:
  - project_id:
    type_status_map:
      Bug:
        To Do: todo-evaluator
        Ready for Development: ready-for-development-evaluator
    codebase:
      repo: "https://github.com/michaelfranz/h6bridge"
      include_patterns:
        - "src/**/*.java"
        - "src/**/*.kt"
        - "src/**/*.kts"
        - "src/**/*.xml"
        - "src/**/*.json"
        - "src/**/*.properties"
        - "src/**/*.cfg"
        - "src/**/*.txt"
        - "src/**/*.md"
        - "src/**/*.mf"
      exclude_patterns:
        - "node_modules/**"
        - "build/**"
    embedding:
      model: "sentence-transformers/all-MiniLM-L6-v2"
    documents:
      urls:
        - "https://realpython.com/python-click/"
        - "https://gist.github.com/ruimaranhao/4e18cbe3dad6f68040c32ed6709090a3"
        - "https://dev.to/devasservice/python-best-practices-writing-clean-efficient-and-maintainable-code-34bj"

