version: '3.8'

services:
  dacrew:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - ./config.yml:/app/config.yml:ro
      - ./.env:/app/.env:ro
      - ./embeddings:/app/embeddings
      - ./logs:/app/logs
    environment:
      - PYTHONPATH=/app
      - ENVIRONMENT=development
      - DACREW_LOG_DIR=/app/logs
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped

  # Optional: Add a simple webhook testing service
  webhook-tester:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ./scripts/webhook-test.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - dacrew
    profiles:
      - testing
